spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate

jwt.secret=amir_task_manager_secret_key_123456

app.name=Task Management System
app.version=1.0.0
app.author=Amirhossein Jahazi
